export class Genres {
    static ROCK = "rock";
    static POP = "pop";
    static RAP = "rap";
    static COUNTRY = "country";
    static JAZZ = "jazz";
    static METAL = "metal";
    static CLASSICAL = "classical";
    static BLUES = "blues";
    static REGGAE = "reggae";
    static FOLK = "folk";
    static ELECTRONIC = "electronic";
    static HIP_HOP = "hip-hop";
    static SOUL = "soul";
    static PUNK = "punk";
    static R_AND_B = "r&b";
    static FUNK = "funk";
    static DISCO = "disco";
    static HOUSE = "house";
    static TECHNO = "techno";
    static TRANCE = "trance";
    static DUBSTEP = "dubstep";
    static DANCE = "dance";
    static INDIE = "indie";
    static ALTERNATIVE = "alternative";
    static OTHER = "other";
}
