export enum Permissions {
    canDeleteComments = 'canDeleteComments',
    canEditListsOfOthers = 'canEditListsOfOthers',
    canEditTracksOfOthers = 'canEditTracksOfOthers',
    canBan = 'canBan',
    canDeleteTracksOfOthers = 'canDeleteTracksOfOthers',
    canDeleteListsOfOthers = 'canDeleteListsOfOthers',
    canCalculateRoyalties = 'canCalculateRoyalties',
    canVerifyUsers = 'canVerifyUsers',
    canViewLogs = 'canViewLogs',
    canViewActionLogs = 'canViewActionLogs',
    canTriggerEventHandling = "canTriggerEventHandling",
    canSetPermissions = "canSetPermissions",
    canViewPayments = "canViewPayments",
}
