import {TrackLike} from "./TrackLike.ts";
import {Album} from "./Album.ts";
import {Playlist} from "./Playlist.ts";
import {Notification} from "./Notification.ts";
import {Comment} from "./Comment.ts";
import {TrackCollaborator} from "./TrackCollaborator.ts";
import {User} from "./User.ts";
import {Repost} from "./Repost.ts";

export interface Track extends Record<string, any> {
    repost_user_id?: number;
    repost?: Repost;
    user?: User;
    comments?: Comment[];
    likes?: TrackLike[];
    playlists?: Playlist[];
    albums?: Album[];
    notifications?: Notification[];
    collaborators?: TrackCollaborator[];
    reposts?: Repost[];
    id: number;
    user_id: number;
    title: string;
    isrc: string;
    artistname: string;
    upc: string;
    visibility: string;
    credits: string;
    loudness_data: string;
    genre: string;
    version: string;
    versionid: number;
    length: number;
    description: string;
    release_date: Date;
    updated_at: Date;
    created_at: Date;
    plays: number;
    secretcode: string;
    monetization: boolean;
    price: number;
    has_cover: boolean;
    processed: boolean;
}